### ISSUE TITLE
Restore does not decrypt files

### ISSUE THREAD

**Issue by ubmarco** [hbons/SparkleShare#1688]
I'm hosting an encrypted Sparkleshare repository. When restoring old file revisions from 'Recent Changes' window, the files are not decrypted. I tested with several file types.

The latest revision (the file in my sync folder) is correctly decrypted.
Any clues?

**Comment by hbons** [comment]
Can't reproduce this anymore. I think this was fixed with https://github.com/hbons/SparkleShare/commit/3a98e968c3551c03494b54b2158b511c1.

**Comment by sihoang** [comment]
I've just experienced the same issue with v3.28.  Downgrading to v2 does not solve the issue.
Reproduce steps:

1. Sync an existing encrypted repo.
2. It will ask for password.  This works!  Enter the password and proceed.
3. Remove the ~/SparkleShare/github.com/<encrypted repo>
4. Remove the corresponding <folder> config in ~/.config/org.sparkleshare.SparkleShare/project.xml
5. Try to re-sync the previous encrypted repo.  It will just pull the encrypted file without asking for the password to decrypt.

**Comment by sihoang** [comment]
Nvm, it was my bad.  I am not supposed to delete the branch x-sparkleshare-encrypted
